import ts from "typescript";

import type { HeaderSegment } from "./types.js";

const HEADER_COMMENT_MARKERS = [
  "@ts-nocheck",
  "@ts-check",
  "eslint-disable",
  "prettier-ignore",
  "generated by",
  "auto-generated",
  "do not edit",
  "@license",
  "spdx-license-identifier",
];

function isHeaderCommentText(text: string): boolean {
  const normalized = text.toLowerCase();
  return HEADER_COMMENT_MARKERS.some((marker) => normalized.includes(marker));
}

function getLine(sourceFile: ts.SourceFile, pos: number): number {
  return sourceFile.getLineAndCharacterOfPosition(pos).line + 1;
}

function resolveShebangEnd(fullText: string): number {
  if (!fullText.startsWith("#!")) return 0;
  const newlineIndex = fullText.indexOf("\n");
  return newlineIndex === -1 ? fullText.length : newlineIndex + 1;
}

function resolveFileHeaderSegments(sourceFile: ts.SourceFile, fullText: string): HeaderSegment[] {
  const segments: HeaderSegment[] = [];
  const shebangEnd = resolveShebangEnd(fullText);

  if (shebangEnd > 0) {
    segments.push({
      startLine: 1,
      endLine: getLine(sourceFile, Math.max(0, shebangEnd - 1)),
      endPos: shebangEnd,
    });
  }

  const commentRanges = ts.getLeadingCommentRanges(fullText, shebangEnd) ?? [];

  for (const range of commentRanges) {
    if (!isHeaderCommentText(fullText.slice(range.pos, range.end))) break;

    segments.push({
      startLine: getLine(sourceFile, range.pos),
      endLine: getLine(sourceFile, range.end),
      endPos: range.end,
    });
  }

  return segments;
}

function resolveAttachedStartLine(
  sourceFile: ts.SourceFile,
  fullText: string,
  node: ts.Node,
  notBeforePos: number,
): number {
  const nodeStart = node.getStart(sourceFile);
  const searchStart = Math.max(node.getFullStart(), notBeforePos);
  const commentRanges = (ts.getLeadingCommentRanges(fullText, searchStart) ?? [])
    .filter((range) => range.pos >= notBeforePos && range.end <= nodeStart);

  if (commentRanges.length === 0) return getLine(sourceFile, nodeStart);

  let cursorPos = nodeStart;
  let attachedStart = nodeStart;

  for (let index = commentRanges.length - 1; index >= 0; index -= 1) {
    const range = commentRanges[index]!;
    const gap = getLine(sourceFile, cursorPos) - getLine(sourceFile, range.end);
    if (gap > 1) break;

    attachedStart = range.pos;
    cursorPos = range.pos;
  }

  return getLine(sourceFile, attachedStart);
}

export { getLine, resolveAttachedStartLine, resolveFileHeaderSegments };
