use napi::Result;
use napi_derive::napi;
use rayon::prelude::*;
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::collections::HashSet;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::Instant;

include!("parts/support.rs");
include!("parts/source_scan.rs");
include!("parts/comment/ranges.rs");
include!("parts/comment/ranges/python.rs");
include!("parts/comment/ranges/qml.rs");
include!("parts/comment/ranges/shell.rs");
include!("parts/comment/stripping.rs");
include!("parts/common_violations.rs");
include!("parts/violation_factories.rs");
include!("parts/folderize.rs");
include!("parts/function/lines.rs");
include!("parts/function/lines/shared.rs");
include!("parts/function/lines/typescript.rs");
include!("parts/formatter.rs");
include!("parts/formatter/masking.rs");
include!("parts/formatter/wrapping/strings.rs");
include!("parts/formatter/wrapping/delimited.rs");
include!("parts/formatter/wrapping.rs");
include!("parts/api.rs");
include!("parts/formatter/tests.rs");
include!("parts/tests.rs");
