use napi::Result;
use napi_derive::napi;
use rayon::prelude::*;
use serde::{Deserialize, Serialize};
use serde_json::json;
use std::collections::{HashMap, HashSet};
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Mutex, OnceLock};
use std::time::Instant;

include!("parts/support.rs");
include!("parts/source_scan.rs");
include!("parts/comment/ranges.rs");
include!("parts/comment/ranges/cpp.rs");
include!("parts/comment/ranges/csharp.rs");
include!("parts/comment/ranges/python.rs");
include!("parts/comment/ranges/qml.rs");
include!("parts/comment/ranges/rust.rs");
include!("parts/comment/ranges/shell.rs");
include!("parts/comment/stripping.rs");
include!("parts/comment/tests.rs");
include!("parts/common_violations.rs");
include!("parts/violation_factories.rs");
include!("parts/structure.rs");
include!("parts/function/lines.rs");
include!("parts/function/lines/shared.rs");
include!("parts/function/lines/typescript.rs");
include!("parts/check/types.rs");
include!("parts/check/common.rs");
include!("parts/check/empty_folders.rs");
include!("parts/check/functions.rs");
include!("parts/check/imports.rs");
include!("parts/check/declarations.rs");
include!("parts/check/declaration_names.rs");
include!("parts/check/structural.rs");
include!("parts/check/dry.rs");
include!("parts/check/rules.rs");
include!("parts/check/rules_extra.rs");
include!("parts/formatter/tokens.rs");
include!("parts/formatter/spacing.rs");
include!("parts/formatter/spacing/rules.rs");
include!("parts/formatter/spacing/state.rs");
include!("parts/formatter/statements.rs");
include!("parts/formatter.rs");
include!("parts/formatter/masking.rs");
include!("parts/formatter/wrapping/strings.rs");
include!("parts/formatter/wrapping/delimited.rs");
include!("parts/formatter/wrapping.rs");
include!("parts/api.rs");
include!("parts/test_support.rs");
include!("parts/formatter/tests.rs");
include!("parts/formatter/wrapping_tests.rs");
include!("parts/structure_tests.rs");
include!("parts/tests.rs");
include!("parts/c_family_tests.rs");
