const DEFAULT_SOURCE_ROOT = "src";
const DEFAULT_SOURCE_EXTENSIONS = [".ts", ".tsx", ".js", ".jsx"];
const DEFAULT_EXCLUDE_DIRS = ["node_modules", "dist", ".vite"];
const DEFAULT_ALIAS_PREFIX = "#";
const DEFAULT_ALIAS_STRATEGY = "random";
const DEFAULT_ALIAS_RANDOM_LENGTH = 12;
const DEFAULT_IMPORTS_REWRITE = true;
const DEFAULT_KEEP_RELATIVE = ["./"];
const DEFAULT_MAX_FILE_LINES_SEVERITY = "error";
const DEFAULT_FOLDERIZE_COMPOUND_FILES_SEVERITY = "error";
const DEFAULT_FOLDERIZE_COMPOUND_FILE_SEPARATORS = ["_", "-"];
const DEFAULT_FOLDERIZE_COMPOUND_FILE_SUFFIXES = ["start"];
const CODE_DISCIPLINE_CONFIG_FILE = "code-discipline.config.json";
const SYNC_IMPORTS_LOG_GROUP = "code-discipline";
const RANDOM_ALIAS_ALPHABET = "abcdefghijklmnopqrstuvwxyz0123456789";
const HASH_ALIAS_LENGTH = 12;

export {
  CODE_DISCIPLINE_CONFIG_FILE,
  DEFAULT_ALIAS_PREFIX,
  DEFAULT_ALIAS_RANDOM_LENGTH,
  DEFAULT_ALIAS_STRATEGY,
  DEFAULT_EXCLUDE_DIRS,
  DEFAULT_FOLDERIZE_COMPOUND_FILES_SEVERITY,
  DEFAULT_FOLDERIZE_COMPOUND_FILE_SEPARATORS,
  DEFAULT_FOLDERIZE_COMPOUND_FILE_SUFFIXES,
  DEFAULT_IMPORTS_REWRITE,
  DEFAULT_KEEP_RELATIVE,
  DEFAULT_MAX_FILE_LINES_SEVERITY,
  DEFAULT_SOURCE_EXTENSIONS,
  DEFAULT_SOURCE_ROOT,
  HASH_ALIAS_LENGTH,
  RANDOM_ALIAS_ALPHABET,
  SYNC_IMPORTS_LOG_GROUP,
};
