const DEFAULT_SOURCE_ROOT = "src";
const DEFAULT_SOURCE_EXTENSIONS = [".ts", ".tsx", ".js", ".jsx"];
const DEFAULT_EXCLUDE_DIRS = ["node_modules", "dist", ".vite"];
const DEFAULT_ALIAS_PREFIX = "#";
const DEFAULT_ALIAS_STRATEGY = "random";
const DEFAULT_ALIAS_RANDOM_LENGTH = 12;
const DEFAULT_RULE_FIX = false;
const DEFAULT_ALLOW_RELATIVE = ["./"];
const DEFAULT_FOLDERIZE_COMPOUND_FILE_SEPARATORS = ["_", "-"];
const CODE_DISCIPLINE_LOG_GROUP = "code-discipline";
const RANDOM_ALIAS_ALPHABET = "abcdefghijklmnopqrstuvwxyz0123456789";
const HASH_ALIAS_LENGTH = 12;

export {
  DEFAULT_ALIAS_PREFIX,
  DEFAULT_ALIAS_RANDOM_LENGTH,
  DEFAULT_ALIAS_STRATEGY,
  DEFAULT_ALLOW_RELATIVE,
  DEFAULT_EXCLUDE_DIRS,
  DEFAULT_FOLDERIZE_COMPOUND_FILE_SEPARATORS,
  DEFAULT_RULE_FIX,
  DEFAULT_SOURCE_EXTENSIONS,
  DEFAULT_SOURCE_ROOT,
  HASH_ALIAS_LENGTH,
  RANDOM_ALIAS_ALPHABET,
  CODE_DISCIPLINE_LOG_GROUP,
};
